import { test, expect } from '@playwright/test'

test('@v2 alarm acknowledgement does not clear the fault and work order closes only after recovery', async ({ page }) => {
  test.setTimeout(90000)
  await page.goto('/devices/CHG-002')
  await page.getByRole('button', { name: '模拟过温', exact: true }).click()
  await expect(page.getByTestId('device-health')).toContainText('过温', { timeout: 8000 })
  const alarms = page.getByTestId('alarm-list')
  await expect(alarms).toContainText('ACTIVE', { timeout: 8000 })
  await alarms.getByRole('button', { name: '确认已知晓' }).first().click()
  await expect(alarms).toContainText('已确认')
  await expect(alarms).toContainText('ACTIVE')
  await page.goto('/agent')
  await page.getByLabel('问题', { exact: true }).fill('分析2号桩最近10分钟过温，创建检修工单')
  await page.getByLabel('允许本次创建检修工单').check()
  await page.getByRole('button', { name: '发送任务' }).click()
  await expect(page.getByTestId('run-status')).toContainText('已完成', { timeout: 12000 })
  const rows = (await (await page.request.get('/api/work-orders?device_id=CHG-002')).json()).data
  expect(rows).toHaveLength(1)
  const id = rows[0].order_id
  await page.goto('/devices/CHG-002')
  const order = page.getByTestId(`work-order-${id}`)
  await order.getByRole('button', { name: '开始处理' }).click()
  await expect(order).toContainText('IN_PROGRESS')
  await order.getByLabel('处理说明').fill('核对模拟器场景，准备恢复并核验新鲜遥测。')
  await order.getByRole('button', { name: '标记已解决' }).click()
  await expect(order).toContainText('RESOLVED')
  await order.getByRole('button', { name: '验证恢复并关闭' }).click()
  await expect(order.getByRole('alert')).toBeVisible()
  await expect(order).toContainText('RESOLVED')
  await page.getByRole('button', { name: '恢复正常', exact: true }).click()
  await expect(page.getByTestId('device-health')).toContainText('正常', { timeout: 8000 })
  await expect.poll(async () => (await (await page.request.get('/api/alarms?device_id=CHG-002&condition=ACTIVE')).json()).data.items.length, { timeout: 18000 }).toBe(0)
  await order.getByRole('button', { name: '验证恢复并关闭' }).click()
  await expect(order).toContainText('CLOSED', { timeout: 8000 })
  await order.getByRole('button', { name: '查看处理记录' }).click()
  await expect(order).toContainText('恢复证据')
})
